Repository angelewilliams/whats-cooking, pull requests merged in 2022-04, with the labels that each got.

#21 Functionality/interact with recipe
  dist/index.html
  src/scripts.js
  src/styles.css
Labels: enhancement, iteration1, Functions

#22 Finalize popup functionality
  dist/index.html
  src/scripts.js
  src/styles.css
Labels: iteration1, Functions

#23 Features/filter recipes
  dist/index.html
  src/classes/RecipeRepository.js
  src/scripts.js
Labels: iteration1

#27 Feature/user class
  dist/index.html
  src/classes/Recipe.js
  src/classes/RecipeRepository.js
  src/classes/User.js
  src/data/users.js
  src/scripts.js
  src/styles.css
  test/Recipe-test.js
  test/User-test.js
Labels: iteration2

#28 Add stylings to css
  src/styles.css
Labels: enhancement, iteration2

#29 Functionality/fetch request promise
  README.md
  src/apiCalls.js
  src/classes/Recipe.js
  src/classes/RecipeRepository.js
  src/classes/User.js
  src/scripts.js
  test/User-test.js
Labels: bug, Classes, Functions

#31 Refactoring/mvp refactoring
  dist/index.html
  src/classes/Ingredient.js
  src/classes/Recipe.js
  src/classes/RecipeRepository.js
  src/classes/User.js
  src/scripts.js
Labels: iteration3, refactor

#33 Refactor tests with sample dataset
  src/data/sampleDatasets.js
  test/Ingredient-test.js
  test/Recipe-test.js
  test/RecipeRepository-test.js
  test/User-test.js
Labels: documentation, refactor

#34 Features/readme
  README.md
Labels: documentation

#36 Functionality/add dynamic event listeners
  dist/index.html
  src/classes/RecipeRepository.js
  src/classes/User.js
  src/scripts.js
Labels: enhancement, Classes, refactor, Functions, data

#35 Final test refactor
  test/RecipeRepository-test.js
  test/User-test.js
Labels: bug, documentation

#37 Remove data files
  src/classes/RecipeRepository.js
Labels: duplicate, refactor

#38 Remove hard coded data files
  src/data/ingredients.js
  src/data/recipes.js
  src/data/users.js
Labels: refactor

#39 Update alt text and add links to README
  README.md
  src/scripts.js
  test/User-test.js
Labels: documentation

#58 Refactor/feedback
  src/apiCalls.js
  src/scripts.js
  src/styles.css
Labels: bug, refactor, Functions, data, part2

#59 Features/Kitchen-class
  src/classes/Kitchen.js
  src/classes/User.js
  src/data/sampleDatasets.js
  src/scripts.js
  test/Kitchen-test.js
Labels: Classes, functions/methods, part2

#61 Add initial kitchen DOM elements
  dist/index.html
  src/styles.css
Labels: enhancement, part2, DOM

#60 Functionality/cook recipes
  src/apiCalls.js
  src/classes/Kitchen.js
  src/classes/User.js
  src/scripts.js
  test/Kitchen-test.js
  test/Recipe-test.js
  test/User-test.js
Labels: bug, classes, data, part2

#62 Features/html css
  dist/index.html
  src/apiCalls.js
  src/classes/Kitchen.js
  src/classes/RecipeRepository.js
  src/classes/User.js
  src/data/sampleDatasets.js
  src/domUpdates.js
  src/scripts.js
  src/styles.css
  test/Kitchen-test.js
Labels: data, part2

#63 Add final JS refactoring
  src/apiCalls.js
  src/classes/Kitchen.js
  src/classes/User.js
  src/scripts.js
  test/Kitchen-test.js
  test/Recipe-test.js
  test/RecipeRepository-test.js
  test/User-test.js
Labels: bug, classes, refactor, functions/methods, data, part2, DOM

#64 Update README
  README.md
  src/images/WCAllRecipes.png
  src/images/WCPopoutRecipe.png
  src/images/WCRecipesToCook.png
  src/images/WCSavedRecipes.png
Labels: data, part2
