Repository angelewilliams/whats-cooking, pull requests merged in 2022-03, with the labels that each got.

#5 Functionality/recipe class
  dist/index.html
  src/classes/RecipeRepository.js
  src/data/recipes.js
  src/styles.css
  test/RecipeRepository-test.js
Labels: iteration1, Classes

#12 Add ingredient class functionality
  src/apiCalls.js
  src/classes/Ingredient.js
  src/classes/RecipeRepository.js
  src/data/ingredients.js
  src/scripts.js
  test/Ingredient-test.js
Labels: enhancement, iteration1, Classes, Functions

#15 Features/recipe repository class
  src/classes/RecipeRepository.js
  src/classes/User.js
  test/Recipe-test.js
  test/RecipeRepository-test.js
  test/User-test.js
Labels: iteration1, refactor

#17 Features/html css
  .DS_Store
  dist/index.html
  src/assets/icon_banner_add.png
  src/assets/icon_banner_remove.png
  src/assets/icon_fire_symbol_lit.png
  src/assets/icon_fire_symbol_unlit.png
  src/assets/image_data.md
  src/classes/RecipeRepository.js
  src/scripts.js
  src/styles.css
Labels: enhancement, iteration1

#20 Add popup window and refine to acceptable visual mvp
  dist/index.html
  src/styles.css
Labels: enhancement, iteration1
